name: Pipeline pruebas "Owner"

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Descargar el proyecto
      uses: actions/checkout@v3
    - name: Set up JDK ${{matrix.java}}
      uses: actions/setup-java@v2
      with:
        java-version: ${{matrix.java}}
        distribution: 'adopt'
        cache: maven
    - name: Compilar con Maven
      run: ./mvnw -B package

    - name: Probar grupo "Owner"
      run: ./mvnw test -Dgroups="Owner"


      

