name: Pipeline pruebas "Visit"

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Descargar el proyecto
      uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: 17
        distribution: 'adopt'
        cache: maven
    - name: Compilar con Maven
      run: ./mvnw -B package -DskipTests

    - name: Probar grupo "Visit"
      run: ./mvnw test -Dgroups="Visit"
